"""add internal volumes in server db

Revision ID: 02245a6b2a14
Revises: 14486dac96da
Create Date: 2022-09-02 10:27:24.697282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02245a6b2a14'
down_revision = '14486dac96da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('internal_volumes', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_server_internal_volumes'), 'server', ['internal_volumes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_internal_volumes'), table_name='server')
    op.drop_column('server', 'internal_volumes')
    # ### end Alembic commands ###
