"""add mandatory_volumes in Server

Revision ID: 14486dac96da
Revises: a48c60d3dfc2
Create Date: 2022-07-14 15:35:47.787360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14486dac96da'
down_revision = 'a48c60d3dfc2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('mandatory_volumes', sa.String(length=300), nullable=True))
    op.create_index(op.f('ix_server_mandatory_volumes'), 'server', ['mandatory_volumes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_mandatory_volumes'), table_name='server')
    op.drop_column('server', 'mandatory_volumes')
    # ### end Alembic commands ###
