"""add info to server

Revision ID: 15ff9bd8e550
Revises: aebb3e2e8914
Create Date: 2022-04-25 10:51:29.555857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15ff9bd8e550'
down_revision = 'aebb3e2e8914'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('os', sa.String(length=30), nullable=True))
    op.add_column('server', sa.Column('raminfo', sa.String(length=30), nullable=True))
    op.add_column('server', sa.Column('rominfo', sa.String(length=30), nullable=True))
    op.add_column('server', sa.Column('modele', sa.String(length=30), nullable=True))
    op.add_column('server', sa.Column('cpuinfo', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_server_cpuinfo'), 'server', ['cpuinfo'], unique=False)
    op.create_index(op.f('ix_server_modele'), 'server', ['modele'], unique=False)
    op.create_index(op.f('ix_server_os'), 'server', ['os'], unique=False)
    op.create_index(op.f('ix_server_raminfo'), 'server', ['raminfo'], unique=False)
    op.create_index(op.f('ix_server_rominfo'), 'server', ['rominfo'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_rominfo'), table_name='server')
    op.drop_index(op.f('ix_server_raminfo'), table_name='server')
    op.drop_index(op.f('ix_server_os'), table_name='server')
    op.drop_index(op.f('ix_server_modele'), table_name='server')
    op.drop_index(op.f('ix_server_cpuinfo'), table_name='server')
    op.drop_column('server', 'cpuinfo')
    op.drop_column('server', 'modele')
    op.drop_column('server', 'rominfo')
    op.drop_column('server', 'raminfo')
    op.drop_column('server', 'os')
    # ### end Alembic commands ###
