"""remove rom info  to server

Revision ID: 3129188dfe20
Revises: 15ff9bd8e550
Create Date: 2022-04-25 12:11:12.390682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3129188dfe20'
down_revision = '15ff9bd8e550'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_server_rominfo', table_name='server')
    op.drop_column('server', 'rominfo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('rominfo', sa.VARCHAR(length=30), nullable=True))
    op.create_index('ix_server_rominfo', 'server', ['rominfo'], unique=False)
    # ### end Alembic commands ###
