"""add public address4

Revision ID: 45f4ce49ab0a
Revises: ea063803053a
Create Date: 2022-04-20 14:30:06.824678

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45f4ce49ab0a'
down_revision = 'ea063803053a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('public_address', sa.String(length=15), nullable=True))
    op.add_column('server', sa.Column('public_name', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_server_public_address'), 'server', ['public_address'], unique=True)
    op.create_index(op.f('ix_server_public_name'), 'server', ['public_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_public_name'), table_name='server')
    op.drop_index(op.f('ix_server_public_address'), table_name='server')
    op.drop_column('server', 'public_name')
    op.drop_column('server', 'public_address')
    # ### end Alembic commands ###
