"""add ServerInfo in models and form again

Revision ID: 746f2bd8b1e3
Revises: eb77f301a32f
Create Date: 2022-07-04 10:47:20.443058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '746f2bd8b1e3'
down_revision = 'eb77f301a32f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_info', sa.Column('server_name', sa.String(length=30), nullable=True))
    op.drop_index('ix_server_info_name', table_name='server_info')
    op.create_index(op.f('ix_server_info_server_name'), 'server_info', ['server_name'], unique=False)
    op.drop_column('server_info', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server_info', sa.Column('name', sa.VARCHAR(length=30), nullable=True))
    op.drop_index(op.f('ix_server_info_server_name'), table_name='server_info')
    op.create_index('ix_server_info_name', 'server_info', ['name'], unique=False)
    op.drop_column('server_info', 'server_name')
    # ### end Alembic commands ###
