"""add linux function

Revision ID: 74f1bb721968
Revises: bd7212494a20
Create Date: 2022-04-26 10:32:37.587929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74f1bb721968'
down_revision = 'bd7212494a20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('system_type', sa.String(length=30), nullable=True))
    op.create_index(op.f('ix_server_system_type'), 'server', ['system_type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_system_type'), table_name='server')
    op.drop_column('server', 'system_type')
    # ### end Alembic commands ###
