"""servers table

Revision ID: 8b04663e5817
Revises: 446f22756a8e
Create Date: 2022-03-31 11:41:30.331708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b04663e5817'
down_revision = '446f22756a8e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=15), nullable=True),
    sa.Column('name', sa.String(length=15), nullable=True),
    sa.Column('user', sa.String(length=15), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_address'), 'server', ['address'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_address'), table_name='server')
    op.drop_table('server')
    # ### end Alembic commands ###
