"""add mount_volumes in Server

Revision ID: a48c60d3dfc2
Revises: 746f2bd8b1e3
Create Date: 2022-07-08 14:58:43.410485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a48c60d3dfc2'
down_revision = '746f2bd8b1e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('mount_volumes', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_server_mount_volumes'), 'server', ['mount_volumes'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_mount_volumes'), table_name='server')
    op.drop_column('server', 'mount_volumes')
    # ### end Alembic commands ###
