"""remove unique to public_address

Revision ID: bd7212494a20
Revises: 3129188dfe20
Create Date: 2022-04-25 12:32:33.733026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd7212494a20'
down_revision = '3129188dfe20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_server_public_address', table_name='server')
    op.create_index(op.f('ix_server_public_address'), 'server', ['public_address'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_public_address'), table_name='server')
    op.create_index('ix_server_public_address', 'server', ['public_address'], unique=False)
    # ### end Alembic commands ###
