"""add about_me in Server2

Revision ID: ea063803053a
Revises: f5ddf51a9e13
Create Date: 2022-04-12 15:28:16.849550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea063803053a'
down_revision = 'f5ddf51a9e13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('server', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('server', 'about_me')
    # ### end Alembic commands ###
