"""add ServerInfo in models and form

Revision ID: eb77f301a32f
Revises: 0a57e7aad453
Create Date: 2022-07-01 16:31:23.001892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb77f301a32f'
down_revision = '0a57e7aad453'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('server_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.String(length=30), nullable=True),
    sa.Column('informations', sa.String(length=1000), nullable=True),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_server_info_name'), 'server_info', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_server_info_name'), table_name='server_info')
    op.drop_table('server_info')
    # ### end Alembic commands ###
