"""add index=true in Post.device

Revision ID: f5ddf51a9e13
Revises: 2d26e09b5316
Create Date: 2022-04-12 11:25:46.467029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5ddf51a9e13'
down_revision = '2d26e09b5316'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_device'), 'post', ['device'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_device'), table_name='post')
    # ### end Alembic commands ###
